name: Test installations

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  gha:
    runs-on: "ubuntu-latest"
    steps:
    - uses: untitaker/hyperlink@0.1.44
      with:
        args: --help
